// <auto-generated />
using System;
using System.Net;
using Atlas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atlas.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AtlasDbContext))]
    [Migration("20260715164829_SecurityRecipientAndIdempotency")]
    partial class SecurityRecipientAndIdempotency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atlas.Domain.Entities.ActionRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("AccessTokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("access_token_hash");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("FirstViewedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("first_viewed_at");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<int>("OtpAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("otp_attempt_count");

                    b.Property<byte[]>("OtpCodeHash")
                        .HasColumnType("bytea")
                        .HasColumnName("otp_code_hash");

                    b.Property<DateTimeOffset?>("OtpExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("otp_expires_at");

                    b.Property<bool>("OtpRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("otp_required");

                    b.Property<DateTimeOffset?>("OtpVerifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("otp_verified_at");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("submitted_at");

                    b.Property<DateTimeOffset?>("TokenExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("token_expires_at");

                    b.HasKey("Id")
                        .HasName("pk_action_recipients");

                    b.HasIndex("AccessTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_recipients_token_hash");

                    b.HasIndex("ActionId", "Status")
                        .HasDatabaseName("ix_recipients_action_status");

                    b.ToTable("action_recipients", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AdminSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("key");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<short>("Scope")
                        .HasColumnType("smallint")
                        .HasColumnName("scope");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.HasKey("Id")
                        .HasName("pk_admin_settings");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_admin_settings_updated_by_user_id");

                    b.HasIndex("Category", "Key")
                        .IsUnique()
                        .HasDatabaseName("uq_admin_settings_global_category_key")
                        .HasFilter("organization_id IS NULL");

                    b.HasIndex("OrganizationId", "Category", "Key")
                        .IsUnique()
                        .HasDatabaseName("uq_admin_settings_org_category_key")
                        .HasFilter("organization_id IS NOT NULL");

                    b.ToTable("admin_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a573c60e-6d96-4204-a451-4c4c3f66ac31"),
                            Category = "files",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSecret = false,
                            Key = "maxUploadBytes",
                            Scope = (short)1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "10485760"
                        },
                        new
                        {
                            Id = new Guid("c17b8e86-e95f-4d19-a375-17672ce7c390"),
                            Category = "files",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSecret = false,
                            Key = "uploadUrlMinutes",
                            Scope = (short)1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "10"
                        },
                        new
                        {
                            Id = new Guid("cc13c863-f4e5-4c34-9029-9d77b82d713b"),
                            Category = "files",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSecret = false,
                            Key = "downloadUrlMinutes",
                            Scope = (short)1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "5"
                        },
                        new
                        {
                            Id = new Guid("25ff9a4f-61f3-4460-a92e-5b0784154b2f"),
                            Category = "security",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSecret = false,
                            Key = "recipientTokenDays",
                            Scope = (short)1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "30"
                        },
                        new
                        {
                            Id = new Guid("8c967ee1-9233-4edc-aa96-961ea6eca16e"),
                            Category = "retention",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSecret = false,
                            Key = "defaultRetentionDays",
                            Scope = (short)1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "365"
                        });
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_api_keys");

                    b.HasIndex("OrganizationId", "KeyPrefix")
                        .HasDatabaseName("ix_api_keys_org_prefix");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("mfa_enabled");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_id");

                    b.Property<string>("ActorId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_id");

                    b.Property<short>("ActorType")
                        .HasColumnType("smallint")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("ActionId", "CreatedAt")
                        .HasDatabaseName("ix_audit_action_created");

                    b.HasIndex("OrganizationId", "CreatedAt")
                        .HasDatabaseName("ix_audit_org_created");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ChecklistAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("due_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PublicReference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("public_reference");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_json");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<Guid?>("TemplateVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_version_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_actions");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_actions_created_by_user_id");

                    b.HasIndex("PublicReference")
                        .IsUnique()
                        .HasDatabaseName("uq_actions_public_reference");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_actions_template_id");

                    b.HasIndex("TemplateVersionId")
                        .HasDatabaseName("ix_actions_template_version_id");

                    b.HasIndex("OrganizationId", "DueAt")
                        .HasDatabaseName("ix_actions_org_due")
                        .HasFilter("deleted_at IS NULL AND due_at IS NOT NULL AND status IN (2, 3)");

                    b.HasIndex("OrganizationId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_actions_org_status");

                    b.ToTable("actions", null, t =>
                        {
                            t.HasCheckConstraint("ck_actions_due_after_created", "due_at IS NULL OR due_at >= created_at");
                        });
                });

            modelBuilder.Entity("Atlas.Domain.Entities.DraftResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActionRecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_recipient_id");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBySession")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_session");

                    b.Property<string>("ValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_draft_responses");

                    b.HasIndex("RequirementId")
                        .HasDatabaseName("ix_draft_responses_requirement_id");

                    b.HasIndex("ActionRecipientId", "RequirementId")
                        .IsUnique()
                        .HasDatabaseName("uq_draft_recipient_requirement");

                    b.ToTable("draft_responses", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.FileAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_id");

                    b.Property<Guid?>("ActionRecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_recipient_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Extension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("extension");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<DateTimeOffset?>("RetentionUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("retention_until");

                    b.Property<DateTimeOffset?>("ScanCompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("scan_completed_at");

                    b.Property<string>("ScanEngine")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scan_engine");

                    b.Property<short>("ScanStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("scan_status");

                    b.Property<byte[]>("Sha256Hash")
                        .HasColumnType("bytea")
                        .HasColumnName("sha256hash");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.HasKey("Id")
                        .HasName("pk_file_assets");

                    b.HasIndex("ActionId")
                        .HasDatabaseName("ix_file_assets_action_id");

                    b.HasIndex("ActionRecipientId")
                        .HasDatabaseName("ix_file_assets_action_recipient_id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("uq_file_assets_storage_key");

                    b.HasIndex("OrganizationId", "CreatedAt")
                        .HasDatabaseName("ix_files_org_created");

                    b.HasIndex("ScanStatus", "CreatedAt")
                        .HasDatabaseName("ix_files_scan_status");

                    b.ToTable("file_assets", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("key");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_json");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_expiry");

                    b.HasIndex("OrganizationId", "Key")
                        .IsUnique()
                        .HasDatabaseName("uq_idempotency_records_org_key");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActionRecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_recipient_id");

                    b.Property<short>("Channel")
                        .HasColumnType("smallint")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("delivered_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_message_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_key");

                    b.HasKey("Id")
                        .HasName("pk_notification_deliveries");

                    b.HasIndex("ActionRecipientId")
                        .HasDatabaseName("ix_notification_deliveries_action_recipient_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_notification_deliveries_organization_id");

                    b.ToTable("notification_deliveries", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccentColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("accent_color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("default_language");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("LogoFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("logo_file_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PrivacyStatement")
                        .HasColumnType("text")
                        .HasColumnName("privacy_statement");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("retention_days");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("LogoFileId")
                        .HasDatabaseName("ix_organizations_logo_file_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_organizations_slug");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.OrganizationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("InvitedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("invited_at");

                    b.Property<DateTimeOffset?>("JoinedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_users_user_id");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_organization_users_org_user");

                    b.ToTable("organization_users", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.RecipientAccessSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActionRecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_recipient_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_seen_at");

                    b.Property<bool>("OtpVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("otp_verified");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("SessionTokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("session_token_hash");

                    b.HasKey("Id")
                        .HasName("pk_recipient_access_sessions");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_recipient_access_sessions_token_hash");

                    b.HasIndex("ActionRecipientId", "ExpiresAt")
                        .HasDatabaseName("ix_recipient_access_sessions_recipient_expiry");

                    b.ToTable("recipient_access_sessions", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ReminderSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActionRecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_recipient_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("TriggerAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("trigger_at");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_reminder_schedules");

                    b.HasIndex("ActionRecipientId")
                        .HasDatabaseName("ix_reminder_schedules_action_recipient_id");

                    b.HasIndex("Status", "TriggerAt")
                        .HasDatabaseName("ix_reminders_due");

                    b.ToTable("reminder_schedules", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Requirement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_id");

                    b.Property<string>("ConditionJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("condition_json");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration_json");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("label");

                    b.Property<Guid?>("SourceTemplateRequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_template_requirement_id");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<string>("ValidationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_json");

                    b.HasKey("Id")
                        .HasName("pk_requirements");

                    b.HasIndex("SourceTemplateRequirementId")
                        .HasDatabaseName("ix_requirements_source_template_requirement_id");

                    b.HasIndex("ActionId", "DisplayOrder")
                        .HasDatabaseName("ix_requirements_action_order");

                    b.HasIndex("ActionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("uq_requirements_action_key");

                    b.ToTable("requirements", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_id");

                    b.Property<Guid>("ActionRecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_recipient_id");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<string>("ReviewComment")
                        .HasColumnType("text")
                        .HasColumnName("review_comment");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("submitted_at");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_submissions");

                    b.HasIndex("ActionRecipientId")
                        .HasDatabaseName("ix_submissions_action_recipient_id");

                    b.HasIndex("ReviewedByUserId")
                        .HasDatabaseName("ix_submissions_reviewed_by_user_id");

                    b.HasIndex("ActionId", "VersionNumber")
                        .HasDatabaseName("ix_submissions_action_version");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.SubmissionFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FileAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_asset_id");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_id");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.HasKey("Id")
                        .HasName("pk_submission_files");

                    b.HasIndex("FileAssetId")
                        .HasDatabaseName("ix_submission_files_file_asset_id");

                    b.HasIndex("RequirementId")
                        .HasDatabaseName("ix_submission_files_requirement_id");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ix_submission_files_submission_id");

                    b.ToTable("submission_files", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.SubmissionResponseEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_id");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<string>("ValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.HasKey("Id")
                        .HasName("pk_submission_responses");

                    b.HasIndex("RequirementId")
                        .HasDatabaseName("ix_submission_responses_requirement_id");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ix_submission_responses_submission_id");

                    b.ToTable("submission_responses", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_templates_created_by_user_id");

                    b.HasIndex("CurrentVersionId")
                        .HasDatabaseName("ix_templates_current_version_id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_templates_org_name");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TemplateRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConditionJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("condition_json");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration_json");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("label");

                    b.Property<Guid>("TemplateVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_version_id");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<string>("ValidationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_json");

                    b.HasKey("Id")
                        .HasName("pk_template_requirements");

                    b.HasIndex("TemplateVersionId", "DisplayOrder")
                        .HasDatabaseName("ix_template_requirements_version_order");

                    b.HasIndex("TemplateVersionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("uq_template_requirements_version_key");

                    b.ToTable("template_requirements", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_json");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_template_versions");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_template_versions_created_by_user_id");

                    b.HasIndex("TemplateId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_template_versions_template_version");

                    b.ToTable("template_versions", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.UsageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_usage_events");

                    b.HasIndex("ActionId")
                        .HasDatabaseName("ix_usage_events_action_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_usage_events_idempotency_key");

                    b.HasIndex("OrganizationId", "OccurredAt")
                        .HasDatabaseName("ix_usage_org_period");

                    b.ToTable("usage_events", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("ResponseExcerpt")
                        .HasColumnType("text")
                        .HasColumnName("response_excerpt");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("WebhookEndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("webhook_endpoint_id");

                    b.HasKey("Id")
                        .HasName("pk_webhook_deliveries");

                    b.HasIndex("WebhookEndpointId")
                        .HasDatabaseName("ix_webhook_deliveries_webhook_endpoint_id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_webhook_retry");

                    b.ToTable("webhook_deliveries", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.WebhookEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string[]>("EventTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("event_types");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<byte[]>("SecretCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_ciphertext");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_webhook_endpoints");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_webhook_endpoints_organization_id");

                    b.ToTable("webhook_endpoints", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ActionRecipient", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.ChecklistAction", "Action")
                        .WithMany("Recipients")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_action_recipients_actions_action_id");

                    b.Navigation("Action");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AdminSetting", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_admin_settings_organizations_organization_id");

                    b.HasOne("Atlas.Domain.Entities.AppUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_admin_settings_users_updated_by_user_id");

                    b.Navigation("Organization");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Organization", "Organization")
                        .WithMany("ApiKeys")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_api_keys_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AuditEvent", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.ChecklistAction", "Action")
                        .WithMany("AuditEvents")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_events_actions_action_id");

                    b.HasOne("Atlas.Domain.Entities.Organization", "Organization")
                        .WithMany("AuditEvents")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_events_organizations_organization_id");

                    b.Navigation("Action");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ChecklistAction", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_actions_users_created_by_user_id");

                    b.HasOne("Atlas.Domain.Entities.Organization", "Organization")
                        .WithMany("Actions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_actions_organizations_organization_id");

                    b.HasOne("Atlas.Domain.Entities.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_actions_templates_template_id");

                    b.HasOne("Atlas.Domain.Entities.TemplateVersion", "TemplateVersion")
                        .WithMany()
                        .HasForeignKey("TemplateVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_actions_template_versions_template_version_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Organization");

                    b.Navigation("Template");

                    b.Navigation("TemplateVersion");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.DraftResponse", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.ActionRecipient", "ActionRecipient")
                        .WithMany("DraftResponses")
                        .HasForeignKey("ActionRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_draft_responses_action_recipients_action_recipient_id");

                    b.HasOne("Atlas.Domain.Entities.Requirement", "Requirement")
                        .WithMany("DraftResponses")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_draft_responses_requirements_requirement_id");

                    b.Navigation("ActionRecipient");

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.FileAsset", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.ChecklistAction", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_file_assets_actions_action_id");

                    b.HasOne("Atlas.Domain.Entities.ActionRecipient", "ActionRecipient")
                        .WithMany()
                        .HasForeignKey("ActionRecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_file_assets_action_recipients_action_recipient_id");

                    b.HasOne("Atlas.Domain.Entities.Organization", "Organization")
                        .WithMany("Files")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_file_assets_organizations_organization_id");

                    b.Navigation("Action");

                    b.Navigation("ActionRecipient");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_idempotency_records_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.NotificationDelivery", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.ActionRecipient", "ActionRecipient")
                        .WithMany()
                        .HasForeignKey("ActionRecipientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notification_deliveries_action_recipients_action_recipient_");

                    b.HasOne("Atlas.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_deliveries_organizations_organization_id");

                    b.Navigation("ActionRecipient");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Organization", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.FileAsset", "LogoFile")
                        .WithMany()
                        .HasForeignKey("LogoFileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_organizations_file_assets_logo_file_id");

                    b.Navigation("LogoFile");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.OrganizationUser", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_users_organizations_organization_id");

                    b.HasOne("Atlas.Domain.Entities.AppUser", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_users_users_user_id");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.RecipientAccessSession", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.ActionRecipient", "ActionRecipient")
                        .WithMany("AccessSessions")
                        .HasForeignKey("ActionRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipient_access_sessions_action_recipients_action_recipien");

                    b.Navigation("ActionRecipient");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ReminderSchedule", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.ActionRecipient", "ActionRecipient")
                        .WithMany("ReminderSchedules")
                        .HasForeignKey("ActionRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reminder_schedules_action_recipients_action_recipient_id");

                    b.Navigation("ActionRecipient");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Requirement", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.ChecklistAction", "Action")
                        .WithMany("Requirements")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_requirements_actions_action_id");

                    b.HasOne("Atlas.Domain.Entities.TemplateRequirement", "SourceTemplateRequirement")
                        .WithMany()
                        .HasForeignKey("SourceTemplateRequirementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_requirements_template_requirements_source_template_requirem");

                    b.Navigation("Action");

                    b.Navigation("SourceTemplateRequirement");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Submission", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.ChecklistAction", "Action")
                        .WithMany("Submissions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_actions_action_id");

                    b.HasOne("Atlas.Domain.Entities.ActionRecipient", "ActionRecipient")
                        .WithMany("Submissions")
                        .HasForeignKey("ActionRecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_action_recipients_action_recipient_id");

                    b.HasOne("Atlas.Domain.Entities.AppUser", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_submissions_users_reviewed_by_user_id");

                    b.Navigation("Action");

                    b.Navigation("ActionRecipient");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.SubmissionFile", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.FileAsset", "FileAsset")
                        .WithMany()
                        .HasForeignKey("FileAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submission_files_file_assets_file_asset_id");

                    b.HasOne("Atlas.Domain.Entities.Requirement", "Requirement")
                        .WithMany()
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submission_files_requirements_requirement_id");

                    b.HasOne("Atlas.Domain.Entities.Submission", "Submission")
                        .WithMany("Files")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submission_files_submissions_submission_id");

                    b.Navigation("FileAsset");

                    b.Navigation("Requirement");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.SubmissionResponseEntry", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Requirement", "Requirement")
                        .WithMany("SubmissionResponses")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submission_responses_requirements_requirement_id");

                    b.HasOne("Atlas.Domain.Entities.Submission", "Submission")
                        .WithMany("Responses")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submission_responses_submissions_submission_id");

                    b.Navigation("Requirement");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Template", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_templates_users_created_by_user_id");

                    b.HasOne("Atlas.Domain.Entities.TemplateVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_templates_template_versions_current_version_id");

                    b.HasOne("Atlas.Domain.Entities.Organization", "Organization")
                        .WithMany("Templates")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_templates_organizations_organization_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("CurrentVersion");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TemplateRequirement", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.TemplateVersion", "TemplateVersion")
                        .WithMany("Requirements")
                        .HasForeignKey("TemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_requirements_template_versions_template_version_id");

                    b.Navigation("TemplateVersion");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TemplateVersion", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_template_versions_users_created_by_user_id");

                    b.HasOne("Atlas.Domain.Entities.Template", "Template")
                        .WithMany("Versions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_template_versions_templates_template_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.UsageEvent", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.ChecklistAction", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_usage_events_actions_action_id");

                    b.HasOne("Atlas.Domain.Entities.Organization", "Organization")
                        .WithMany("UsageEvents")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usage_events_organizations_organization_id");

                    b.Navigation("Action");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.WebhookDelivery", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.WebhookEndpoint", "WebhookEndpoint")
                        .WithMany("Deliveries")
                        .HasForeignKey("WebhookEndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_webhook_deliveries_webhook_endpoints_webhook_endpoint_id");

                    b.Navigation("WebhookEndpoint");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.WebhookEndpoint", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Organization", "Organization")
                        .WithMany("WebhookEndpoints")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_webhook_endpoints_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ActionRecipient", b =>
                {
                    b.Navigation("AccessSessions");

                    b.Navigation("DraftResponses");

                    b.Navigation("ReminderSchedules");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ChecklistAction", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("Recipients");

                    b.Navigation("Requirements");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("ApiKeys");

                    b.Navigation("AuditEvents");

                    b.Navigation("Files");

                    b.Navigation("Members");

                    b.Navigation("Templates");

                    b.Navigation("UsageEvents");

                    b.Navigation("WebhookEndpoints");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Requirement", b =>
                {
                    b.Navigation("DraftResponses");

                    b.Navigation("SubmissionResponses");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Submission", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Template", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TemplateVersion", b =>
                {
                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.WebhookEndpoint", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
